### PR TITLE
Update 1MB-EssentialsX-cmds.yml

### PR DESCRIPTION
**Pull request by MrCrazys**
Added an error message when players try to type the internal command, /_nocmifeature, without any arguments.

### CODE REVIEW

**Comment by mrfloris** [comment]
Hey, thank you for the contribution. Before I merge it (looks fine) can you confirm that you've tested this with the commands?

**Comment by MrCrazys** [comment]
Yes, I have, and it seems to work fine from what I can see.

**Comment by mrfloris** [comment]
> Yes, I have, and it seems to work fine from what I can see.

Glad to hear, could you perhaps test with this:

Additionally, you can extend the check `  - statement:check1! check:$1!=null!` with this trick; `$check:$1!=[playerName]` because when another command is remote called, it will be true, but when it's run by a player, it will be false. 

```
  - statement:check1! check:$1!=null! $check:$1!=[playerName]
```

**Comment by MrCrazys** [comment]
Yes, that works too.

**Pull request merged**
