### PR TITLE
Added /cmi exp and /cmi kit to /gcmd

### PR DESCRIPTION
**Pull request by MrCrazys**
* Added optional -s parameter for commands that support it natively.

### CODE REVIEW

**Review by mrfloris — CHANGES_REQUESTED** [review]
While I support adding the `-s` options, via an additional parameter, I think it is important to be very specific where possible. If it's one param to add like `-s` then using something like `$2-` is overreach. Allowing them to include additional information which could malform the final command. Even if it is unlikely. Moving forward I recommend using `$2` or `$3` and another `$2-` or `$3-` .. (bit hard to explain, but I hope you understand what I mean)

If you can make those changes first, that would be welcomed. And don't forget to check that these commands then still work as expected, since `$2-` might need to be `$2 $3` specifically. 

If however there's a reason to use the `-` instead of specific additional parameter, i'd love to hear it (maybe I'm overlooking something)

**Review by MrCrazys — COMMENTED** [review]
* Removed `-` argument to avoid malformed commands.

**Review by mrfloris — APPROVED** [review]
looks fine, thanks for testing too

**Comment by MrCrazys** [comment]
No problem.

**Pull request merged**
