### PR TITLE
Add command suggestions

### PR DESCRIPTION
**Pull request by MrCrazys**

### CODE REVIEW

**Review by mrfloris — COMMENTED** [review]
<AutoPage><AutoAlias><NoReqPermission>

I don't really want to auto alias these .txt files, they are more sub-files from an index.  Can you remove that before I approve it?

And you beat me to it again, to convert the outdated ones with the new internal cmi ones.

**Comment by MrCrazys** [comment]
My apologies, I didn't realise it was there. I didn't mean to add it.

**Review by mrfloris — APPROVED** [review]
I see we got an update for it, thank you.

**Review by mrfloris — APPROVED** [review]
Excellent. Thanks

**Pull request merged**
